In [1]:
import pandas as pd

In [5]:
pd.read_csv("../data/antennes/data.csv",sep=",")

,Unnamed: 0,ms_location,latitude,longitude,localite
0,0,608-01-00017-00011,14.668258,-17.433069,DAKAR PLATEAU/DAKAR/DAKAR
1,1,608-01-00043-00000,14.669869,-17.439786,DAKAR PLATEAU/DAKAR/DAKAR
2,2,608-01-00078-00006,14.682110,-17.458659,DAKAR PLATEAU/DAKAR/DAKAR
3,3,608-01-00090-00002,14.715050,-17.481397,ALMADIES/DAKAR/DAKAR
4,4,608-01-00101-21261,14.679594,-17.454836,DAKAR PLATEAU/DAKAR/DAKAR
...,...,...,...,...,...
995,995,608-01-09024-60625,14.475463,-17.037907,SINDIA/MBOUR/THIES
996,996,608-01-09024-60936,14.552137,-17.062898,SINDIA/MBOUR/THIES
997,997,608-01-09025-00655,14.710017,-17.442348,GRAND DAKAR/DAKAR/DAKAR
998,998,608-01-09025-19172,14.682112,-17.445676,DAKAR PLATEAU/DAKAR/DAKAR
999,999,608-01-09025-36712,14.712133,-17.445583,GRAND DAKAR/DAKAR/DAKAR